### ISSUE TITLE
Support argument types for `.js` files.

### ISSUE THREAD

**Issue by jespertheend** [denoland/docland#67] opened 2021-12-24 16:43 UTC
In https://doc.deno.land/https://deno.land/x/fake_imports@v0.0.5/mod.js/~/Importer#fakeModule for example, it shows up as
```
fakeModule(url, moduleImplementation)
```
even though in the source the parameter types are provided via jsdoc:
```js
/**
 * Fakes a module.
 * @param {string | URL} url should be relative to the `importMeta` argument
 * provided in the {@link constructor}.
 * @param {string} moduleImplementation The code to replace the imported content with.
 */
```

**Comment by kitsonk** [comment] 2021-12-24 19:47
Duplicate of denoland/deno_doc#137

**Closed by kitsonk** 2021-12-24 19:47 UTC
Labels: duplicate
