### ISSUE TITLE
indentation messed up in jose's docs

### ISSUE THREAD

**Issue by ry** [denoland/docland#74] opened 2022-01-04 00:28 UTC
https://doc.deno.land/https://deno.land/x/jose@v4.3.7/index.ts

<img width="1307" alt="Screen Shot 2022-01-03 at 7 27 36 PM" src="https://user-images.githubusercontent.com/80/147994352-65f1e407-24d0-4472-b892-ca1e6acfea96.png">

https://deno.land/x/jose@v4.3.7/jwe/compact/encrypt.ts#L10-L23

**Comment by jaydenseric** [comment] 2022-01-04 00:34
Not sure if this is the cause, but TypeScript has a bug where using an `@example` caption (with or without `<caption>`) causes indentation within the example to collapse:

https://github.com/microsoft/TypeScript/issues/43955

**Comment by kitsonk** [comment] 2022-01-04 01:58
It doesn't have anything to do with TypeScript...  The parsing of `@example` JSDoc is totally independent of `tsc`.

**Comment by kitsonk** [comment] 2022-01-05 20:48
A user has identified the issue further upstream in https://github.com/denoland/deno_doc/issues/229 so let's address it there.

Duplicate of denoland/deno_doc#229

**Closed by kitsonk** 2022-01-05 20:48 UTC
Labels: duplicate
