### ISSUE TITLE
500 error on /x/mongo's Filter type

### ISSUE THREAD

**Issue by AnInternetTroll** [denoland/docland#71] opened 2021-12-29 21:49 UTC
https://doc.deno.land/https://deno.land/x/mongo@v0.29.0/mod.ts/~/Filter returns `Internal Server Error`

**Comment by kitsonk** [comment] 2021-12-29 22:46
This is the same root cause as #68 which I am fixing now.

Duplicate of #68

**Closed by kitsonk** 2021-12-29 22:46 UTC
Labels: bug, duplicate, needs investigation
